### ISSUE TITLE
你好，亲爱的作者

### ISSUE THREAD

**Issue by qiaoD** [huijianpzh/segmentation-models#1]
能看到有人在复现《DWT》这篇文章太好了，我有些问题想咨询你一下：
1、作者源代码中的matlab文件夹中的三个文件分别是生成什么数据的；
2、我还没有弄清楚，到底需要哪些数据；
3、方便的话，能否加微信15827584675.

万分感谢

**Comment by tianjiu233** [comment]
生成的是算法中间需要的一些中间数据，比如梯度方向这类的。
由于时间关系，我最终并没有完成这个实验。
你可以试着联系作者，发邮件，对方人很nice。
之前我看文章的时候联系过他。
祝好
